# One Terraform configuration per environment: network, database, load balancer and web tier in a single state.
# Terraform loads every .tf file of this folder as one configuration and orders everything from the references between
# modules (module.vpc.vpc_id, module.alb.target_group_arns, ...), so a single `terraform plan` shows the whole environment.
# This file reads the configuration; the infrastructure is in network.tf, database.tf, load_balancer.tf,
# ec2.tf and outputs.tf. Written by hand: these files, inputs.yaml and web-user-data.sh.tftpl. backend.tf is generated by
# the pipeline and the region comes from AWS_REGION.

# Configuration: the values come from the YAML files, and there are none in the .tf files.
locals {
  common = yamldecode(file("${path.module}/../../../common.yaml"))
  inputs = yamldecode(file("${path.module}/inputs.yaml"))

  # The path of this root from the repository root, to find the environment common.yaml lists it under.
  root_path   = trimprefix(abspath(path.module), "${abspath("${path.module}/../../..")}/")
  environment = one([for name, env in local.common.terraform.environments : name if contains(env.roots, local.root_path)])

  # The mandatory tags: the owner and cost center of this root, plus the project and the environment from common.yaml.
  tags = merge(local.inputs.tags, { project = local.common.project, environment = local.environment })
}
