# One Terraform configuration per environment: network, database, load balancer and web tier in a single state.
# Terraform loads every .tf file of this folder as one configuration and orders everything from the references between
# modules (module.vpc.vpc_id, module.alb.target_group_arns, ...), so a single `terraform plan` shows the whole environment.
# This file reads the configuration and validates it; the infrastructure is in network.tf, database.tf, load_balancer.tf,
# web.tf and outputs.tf. Written by hand: these files, inputs.yaml and web-user-data.sh.tftpl. backend.tf is generated by
# the pipeline and the region comes from AWS_REGION.

# Configuration (common.yaml + inputs.yaml)
locals {
  common = yamldecode(file("${path.module}/../../../common.yaml"))
  inputs = yamldecode(file("${path.module}/inputs.yaml"))

  tags = {
    project     = local.common.project
    environment = local.inputs.environment
    owner       = local.inputs.owner
    cost_center = local.inputs.cost_center
  }

  name = "${local.tags.project}-${local.tags.environment}"

  app_port  = local.inputs.ports.app
  db_port   = local.inputs.ports.db
  db_engine = local.inputs.database.engine

  # Named ports usable in the YAML (`port: app`); anything else is parsed as a number.
  named_ports = { app = local.app_port, db = local.db_port, https = 443, http = 80 }

  # NAT gateway is off unless inputs.yaml sets network.nat_gateway_mode (none | single | per_az): it is billed per hour.
  nat_gateway_mode = try(local.inputs.network.nat_gateway_mode, "none")

  has_https = anytrue([for l in values(local.inputs.alb.listeners) : l.protocol == "HTTPS"])
}

# Validation (fails the plan early with a clear message)
# Per-field validation (CIDRs, sizes, enums, ...) is done by the modules' typed inputs.
resource "terraform_data" "config_validation" {
  lifecycle {
    precondition {
      condition     = alltrue([for k in ["environment", "owner", "cost_center", "ports", "network", "security_groups", "database", "alb", "instance_role", "compute"] : contains(keys(local.inputs), k)])
      error_message = "inputs.yaml is missing a required top-level key (environment, owner, cost_center, ports, network, security_groups, database, alb, instance_role, compute)."
    }
    precondition {
      condition     = contains(["dev", "staging", "prod"], local.tags.environment)
      error_message = "inputs.yaml: environment must be one of dev, staging, prod."
    }
    precondition {
      condition     = basename(dirname(abspath(path.module))) == local.tags.environment
      error_message = "inputs.yaml: environment must equal the name of the parent folder of this configuration (<environment>/web-demo)."
    }
    precondition {
      condition     = length(local.inputs.network.availability_zones) == length(local.inputs.network.private_subnet_cidrs) && length(local.inputs.network.availability_zones) == length(local.inputs.network.public_subnet_cidrs)
      error_message = "Provide one public and one private subnet CIDR per availability zone."
    }
    precondition {
      condition     = local.tags.environment != "prod" || local.has_https
      error_message = "prod requires an HTTPS listener in alb.listeners."
    }
    precondition {
      condition     = local.tags.environment != "prod" || (local.inputs.database.deletion_protection && !local.inputs.database.skip_final_snapshot)
      error_message = "prod requires database.deletion_protection = true and skip_final_snapshot = false."
    }
    precondition {
      condition     = local.tags.environment != "prod" || local.nat_gateway_mode == "per_az"
      error_message = "prod requires network.nat_gateway_mode = per_az (one NAT gateway per availability zone)."
    }
    precondition {
      condition     = local.tags.environment != "prod" || length(local.inputs.database.instances) >= 2
      error_message = "prod requires at least two database instances (failover needs a reader)."
    }
    precondition {
      condition     = local.tags.environment != "prod" || local.inputs.compute.min_size >= 2
      error_message = "prod requires compute.min_size >= 2 (the web tier must survive losing an instance)."
    }
    precondition {
      condition     = local.inputs.compute.min_size <= local.inputs.compute.max_size
      error_message = "compute.min_size must not exceed compute.max_size."
    }
  }
}
