# One Terraform configuration per environment: network, database, load balancer and web tier in a single state.
# Terraform orders everything from the references between modules (module.vpc.vpc_id, module.alb.target_group_arns, ...),
# so a single `terraform plan` shows the whole environment, even before anything exists.
# Only this file, inputs.yaml and web-user-data.sh.tftpl are written by hand. provider.tf and versions.tf are global
# (linked from the repo root) and backend.tf is generated by the pipeline.

# ============================================================================
# 1. Configuration (common.yaml + inputs.yaml)
# ============================================================================
locals {
  common = yamldecode(file("${path.module}/../../common.yaml"))
  inputs = yamldecode(file("${path.module}/inputs.yaml"))

  tags = {
    project     = local.common.project
    environment = local.inputs.environment
    owner       = local.inputs.owner
    cost_center = local.inputs.cost_center
  }

  name = "${local.tags.project}-${local.tags.environment}"

  app_port  = local.inputs.ports.app
  db_port   = local.inputs.ports.db
  db_engine = local.inputs.database.engine

  # Named ports usable in the YAML (`port: app`); anything else is parsed as a number.
  named_ports = { app = local.app_port, db = local.db_port, https = 443, http = 80 }

  has_https = anytrue([for l in values(local.inputs.alb.listeners) : l.protocol == "HTTPS"])
}

# ============================================================================
# 2. Validation (fails the plan early with a clear message)
# ============================================================================
# Per-field validation (CIDRs, sizes, enums, ...) is done by the modules' typed inputs.
resource "terraform_data" "config_validation" {
  lifecycle {
    precondition {
      condition     = alltrue([for k in ["environment", "owner", "cost_center", "ports", "network", "security_groups", "database", "alb", "instance_role", "compute"] : contains(keys(local.inputs), k)])
      error_message = "inputs.yaml is missing a required top-level key (environment, owner, cost_center, ports, network, security_groups, database, alb, instance_role, compute)."
    }
    precondition {
      condition     = contains(["dev", "staging", "prod"], local.tags.environment)
      error_message = "inputs.yaml: environment must be one of dev, staging, prod."
    }
    precondition {
      condition     = basename(abspath(path.module)) == local.tags.environment
      error_message = "inputs.yaml: environment must equal the name of the folder this configuration lives in."
    }
    precondition {
      condition     = length(local.inputs.network.availability_zones) == length(local.inputs.network.private_subnet_cidrs) && length(local.inputs.network.availability_zones) == length(local.inputs.network.public_subnet_cidrs)
      error_message = "Provide one public and one private subnet CIDR per availability zone."
    }
    precondition {
      condition     = local.tags.environment != "prod" || local.has_https
      error_message = "prod requires an HTTPS listener in alb.listeners."
    }
    precondition {
      condition     = local.tags.environment != "prod" || (local.inputs.database.deletion_protection && !local.inputs.database.skip_final_snapshot)
      error_message = "prod requires database.deletion_protection = true and skip_final_snapshot = false."
    }
    precondition {
      condition     = local.tags.environment != "prod" || local.inputs.network.nat_gateway_mode == "per_az"
      error_message = "prod requires network.nat_gateway_mode = per_az (one NAT gateway per availability zone)."
    }
    precondition {
      condition     = local.tags.environment != "prod" || length(local.inputs.database.instances) >= 2
      error_message = "prod requires at least two database instances (failover needs a reader)."
    }
    precondition {
      condition     = local.tags.environment != "prod" || local.inputs.compute.min_size >= 2
      error_message = "prod requires compute.min_size >= 2 (the web tier must survive losing an instance)."
    }
    precondition {
      condition     = local.inputs.compute.min_size <= local.inputs.compute.max_size
      error_message = "compute.min_size must not exceed compute.max_size."
    }
  }
}

# ============================================================================
# 3. Network: VPC and the three security groups
# ============================================================================
# SG-to-SG references go one way (app <- alb, db <- app). The reverse directions (alb -> app, app -> db) use the VPC CIDR
# with explicit ports: referencing the groups in both directions would be a dependency cycle.
module "vpc" {
  source = "../../modules/vpc"

  name = local.name
  tags = local.tags

  cidr_block           = local.inputs.network.cidr_block
  availability_zones   = local.inputs.network.availability_zones
  public_subnet_cidrs  = local.inputs.network.public_subnet_cidrs
  private_subnet_cidrs = local.inputs.network.private_subnet_cidrs
  nat_gateway_mode     = local.inputs.network.nat_gateway_mode

  depends_on = [terraform_data.config_validation]
}

# One security group per tier.
module "alb_sg" {
  source = "../../modules/security-group"

  name        = "${local.name}-alb"
  description = local.inputs.security_groups.alb.description
  vpc_id      = module.vpc.vpc_id
  tags        = local.tags

  allow_public_ingress = try(local.inputs.security_groups.alb.allow_public_ingress, false)

  ingress_rules = {
    for k, r in try(local.inputs.security_groups.alb.ingress, {}) : k => {
      description = r.description
      protocol    = try(r.protocol, "tcp")
      from_port   = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      to_port     = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      cidr_ipv4   = try(r.cidr_ipv4 == "vpc" ? module.vpc.vpc_cidr_block : r.cidr_ipv4, null)
    }
  }

  egress_rules = {
    for k, r in try(local.inputs.security_groups.alb.egress, {}) : k => {
      description = r.description
      protocol    = try(r.protocol, "tcp")
      from_port   = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      to_port     = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      cidr_ipv4   = try(r.cidr_ipv4 == "vpc" ? module.vpc.vpc_cidr_block : r.cidr_ipv4, null)
    }
  }
}

module "app_sg" {
  source = "../../modules/security-group"

  name        = "${local.name}-app"
  description = local.inputs.security_groups.app.description
  vpc_id      = module.vpc.vpc_id
  tags        = local.tags

  ingress_rules = {
    for k, r in try(local.inputs.security_groups.app.ingress, {}) : k => {
      description                  = r.description
      protocol                     = try(r.protocol, "tcp")
      from_port                    = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      to_port                      = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      cidr_ipv4                    = try(r.cidr_ipv4 == "vpc" ? module.vpc.vpc_cidr_block : r.cidr_ipv4, null)
      referenced_security_group_id = try(r.source_sg == "alb" ? module.alb_sg.security_group_id : null, null)
    }
  }

  egress_rules = {
    for k, r in try(local.inputs.security_groups.app.egress, {}) : k => {
      description = r.description
      protocol    = try(r.protocol, "tcp")
      from_port   = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      to_port     = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      cidr_ipv4   = try(r.cidr_ipv4 == "vpc" ? module.vpc.vpc_cidr_block : r.cidr_ipv4, null)
    }
  }
}

module "db_sg" {
  source = "../../modules/security-group"

  name        = "${local.name}-db"
  description = local.inputs.security_groups.db.description
  vpc_id      = module.vpc.vpc_id
  tags        = local.tags

  ingress_rules = {
    for k, r in try(local.inputs.security_groups.db.ingress, {}) : k => {
      description                  = r.description
      protocol                     = try(r.protocol, "tcp")
      from_port                    = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      to_port                      = try(local.named_ports[tostring(r.port)], tonumber(r.port))
      cidr_ipv4                    = try(r.cidr_ipv4 == "vpc" ? module.vpc.vpc_cidr_block : r.cidr_ipv4, null)
      referenced_security_group_id = try(r.source_sg == "app" ? module.app_sg.security_group_id : null, null)
    }
  }
}

# ============================================================================
# 5. Published for other units (SSM)

# ============================================================================
# 4. Database: Aurora (PostgreSQL or MySQL, chosen in inputs.yaml)
# ============================================================================
module "database" {
  source = "../../modules/aurora"

  name = "${local.name}-db"
  tags = local.tags

  engine             = local.db_engine
  engine_version     = local.inputs.database.engine_version
  database_name      = local.inputs.database.database_name
  port               = local.db_port
  subnet_ids         = module.vpc.private_subnet_ids
  security_group_ids = [module.db_sg.security_group_id]

  instances             = local.inputs.database.instances
  instance_class        = local.inputs.database.instance_class
  serverless_v2         = try(local.inputs.database.serverless_v2, null)
  backup_retention_days = local.inputs.database.backup_retention_days
  deletion_protection   = local.inputs.database.deletion_protection
  skip_final_snapshot   = local.inputs.database.skip_final_snapshot
  cluster_parameters    = try(local.inputs.database.cluster_parameters, {})

  depends_on = [terraform_data.config_validation]
}

# ============================================================================
# 5. Load balancer: application load balancer
# ============================================================================
module "alb" {
  source = "../../modules/elb/alb"

  name = local.name
  tags = local.tags

  vpc_id                     = module.vpc.vpc_id
  subnet_ids                 = local.inputs.alb.internal ? module.vpc.private_subnet_ids : module.vpc.public_subnet_ids
  security_group_ids         = [module.alb_sg.security_group_id]
  internal                   = local.inputs.alb.internal
  enable_deletion_protection = local.inputs.alb.deletion_protection

  target_groups = {
    for k, t in local.inputs.alb.target_groups : k => {
      port        = try(local.named_ports[tostring(t.port)], tonumber(t.port))
      protocol    = try(t.protocol, "HTTP")
      target_type = try(t.target_type, "instance")
      health_check = {
        path = try(t.health_check_path, "/")
      }
    }
  }

  listeners = local.inputs.alb.listeners
  rules     = try(local.inputs.alb.rules, {})

  depends_on = [terraform_data.config_validation]
}

# ============================================================================
# 6. Web tier: instance role, launch template and Auto Scaling Group
# ============================================================================
data "aws_iam_policy_document" "read_db_secret" {
  statement {
    sid       = "ReadDatabaseSecret"
    actions   = ["secretsmanager:GetSecretValue"]
    resources = [module.database.master_user_secret_arn]
  }
}

module "instance_role" {
  source = "../../modules/iam"

  name = "${local.name}-web"
  tags = local.tags

  assume_role_services    = local.inputs.instance_role.assume_role_services
  managed_policy_arns     = local.inputs.instance_role.managed_policy_arns
  create_instance_profile = local.inputs.instance_role.create_instance_profile

  inline_policies = {
    for k, v in { read-db-secret = data.aws_iam_policy_document.read_db_secret.json } : k => v
    if local.inputs.instance_role.allow_read_db_secret
  }

  depends_on = [terraform_data.config_validation]
}

module "web_template" {
  source = "../../modules/ec2/launch-template"

  name = "${local.name}-web"
  tags = local.tags

  instance_type             = local.inputs.compute.instance_type
  ami_id                    = try(local.inputs.compute.ami_id, null)
  root_volume_size_gb       = local.inputs.compute.root_volume_size_gb
  security_group_ids        = [module.app_sg.security_group_id]
  iam_instance_profile_name = module.instance_role.instance_profile_name

  user_data = templatefile("${path.module}/web-user-data.sh.tftpl", {
    app_port      = local.app_port
    db_host       = module.database.endpoint
    db_port       = local.db_port
    db_name       = local.inputs.database.database_name
    db_secret_arn = module.database.master_user_secret_arn
  })
}

module "web_asg" {
  source = "../../modules/ec2/asg"

  name = "${local.name}-web"
  tags = local.tags

  subnet_ids              = module.vpc.private_subnet_ids
  launch_template_id      = module.web_template.launch_template_id
  launch_template_version = module.web_template.latest_version
  min_size                = local.inputs.compute.min_size
  desired_size            = local.inputs.compute.desired_size
  max_size                = local.inputs.compute.max_size
  target_group_arns       = [module.alb.target_group_arns[local.inputs.compute.target_group]]

  health_check_type         = local.inputs.compute.health_check_type
  health_check_grace_period = try(local.inputs.compute.health_check_grace_period, 300)
  enable_instance_refresh   = try(local.inputs.compute.enable_instance_refresh, true)
  scaling_policies          = try(local.inputs.compute.scaling_policies, {})
}

# ============================================================================
# 7. Outputs
# ============================================================================
output "vpc_id" {
  description = "ID of the VPC."
  value       = module.vpc.vpc_id
}

output "alb_dns_name" {
  description = "DNS name of the load balancer."
  value       = module.alb.dns_name
}

output "database_endpoint" {
  description = "Aurora writer endpoint."
  value       = module.database.endpoint
}

output "database_reader_endpoint" {
  description = "Aurora reader endpoint."
  value       = module.database.reader_endpoint
}

output "database_secret_arn" {
  description = "Secrets Manager ARN with the generated master credentials."
  value       = module.database.master_user_secret_arn
}

output "autoscaling_group_name" {
  description = "Name of the web tier Auto Scaling Group."
  value       = module.web_asg.autoscaling_group_name
}

output "summary" {
  description = "Environment summary derived from the YAML."
  value = {
    name           = local.name
    environment    = local.tags.environment
    nat_mode       = local.inputs.network.nat_gateway_mode
    alb_internal   = local.inputs.alb.internal
    https_enabled  = local.has_https
    db_engine      = local.db_engine
    db_instances   = length(local.inputs.database.instances)
    db_deletion_on = local.inputs.database.deletion_protection
    web_min_size   = local.inputs.compute.min_size
    web_max_size   = local.inputs.compute.max_size
  }
}
